version: 0.0
os: linux
files:
  - source: / # destination으로 이동할 파일들 경로
    destination: /home/ubuntu/deploy # 파일이 저장될 EC2 인스턴스 경로
    overwrite: yes
permissions:
  - object: /home/ubuntu/deploy
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
